version: '3'

services:
  signalr-sample.redis:
    image: redis
    ports:
      - "6379:6379"
  signalr-sample.web1:
    image: signalr-sample.web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8500:80"
    depends_on:
      - signalr-sample.redis
    links:
      - signalr-sample.redis
  signalr-sample.web2:
    image: signalr-sample.web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8501:80"
    depends_on:
      - signalr-sample.redis
    links:
      - signalr-sample.redis